###
POST http://localhost:8081/api/scraper?
    keyword=java

###
POST http://localhost:8081/api/scraper

###
GET localhost:8081/api/jobs?
    keyword=Dotnet

###
GET localhost:8081/api/jobs

###
GET localhost:8081/api/jobs/8

###
GET http://localhost:8081/api/jobs?
    keyword=java&
    pageNo=0&
    pageSize=15

###
GET http://localhost:8081/api/jobs?
    pageNo=0&
    pageSize=10